### ISSUE TITLE
RPC no longer accepts JSON lists

### ISSUE THREAD

**Issue by shinyfoil** [icon-project/icon-rpc-server#141]
It appears that something in the 1.5.0 release changed the behaviour of the API such that it no longer accepts lists of JSON request objects.

Previously, it was possible to send something like:

```
[
    {
        "jsonrpc": "2.0",
        "method": "icx_getBlockByHeight",
        "id": 1,
        "params": {
            "height": "0x0"
        }
    },
    {
        "jsonrpc": "2.0",
        "method": "icx_getBlockByHeight",
        "id": 2,
        "params": {
            "height": "0x1"
        }
    }
]
```

And the API would respond with a list of the responses to each of the request objects. Now, the server responds with a 500 error and the trace in the node's logs is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/usr/local/lib/python3.7/site-packages/iconrpcserver/dispatcher/v3/version3.py", line 59, in dispatch
    req_json["params"] = {"context": context}
TypeError: list indices must be integers or slices, not str
```

This change breaks the [data exporter](https://github.com/insight-icon/icon-etl) that we are developing, and removing the batch query feature will create significant node overhead when using the exporter.

**Comment by yakkle** [comment]
@shinyfoil 
Thank you for reporting bug.
We missed to consider batch request when update `jsonrpcsever` library.
It will be fixed ASAP.

**Comment by robcxyz** [comment]
@yakkle 
Do you have a timeline for this by any chance?  We are working on a [grant](https://forum.icon.community/t/grant-application-blockchain-analytics-and-data-pipelines/871) and are held up by this.  Understand you guys are busy. We're just trying to plan out when we can start back up on this. Thanks.

**Comment by yakkle** [comment]
@robc-io 
I started working. It could be applied to the next `hotfix` release.

**Comment by shinyfoil** [comment]
It appears that this bug is back with some of the recent changes. Sending a similar list object to the API returns

```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "No method and/or jsonrpc attribute"
    }
}
```

which, again, breaks the ETL tools we have been working on.

@yakkle

**Comment by goldworm-icon** [comment]
Sorry for your inconvenience.
We will check for this issue.

**Comment by cow-hs** [comment]
The issue needs more time to be analyzed and corrected.
Sorry for your inconvenience.

**Comment by shinyfoil** [comment]
Hi @leeheonseung, just curious if this had been resolved or not?

**Comment by goldworm** [comment]
Recently we applied some message filtering feature to proxy layer to prevent DoS attack and it's why batch requests does not work now.

I will ask infra team about this problem and if it can be resolved with a little effort, everyone will be happy.
Otherwise you need to wait until ICON 2.0 is launched in August or later

**Comment by yakkle** [comment]
@shinyfoil 
This issue resolved by limit 10 batch requests.
